services:
  core:
    image: liaxum/portfolio:latest
    networks:
      - web-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      placement:
        constraints:
          - node.hostname != liaxum-gaming
      labels:
          - "traefik.enable=true"
          - "traefik.swarm.network=web-net"
          - "traefik.http.routers.portfolio.rule=Host(`liaxum.fr`)"
          - "traefik.http.routers.portfolio.entrypoints=websecure"
          - "traefik.http.routers.portfolio.tls=true"
          - "traefik.http.services.portfolio.loadbalancer.server.port=3000"

networks:
  web-net:
    external: true